#!/bin/bash

set -e -u
username=$SUDO_USER
delay=$((60*20)) #20 minutes
uGuid=$(dscl . -read /Users/$username/ GeneratedUID | sed -nE 's/GeneratedUID: (.*$)/\1/p')

if groups "$username" | grep -q -w admin; then
        dscl . -delete /Groups/admin GroupMembers "$uGuid"
        echo "Removed '$username' from admin. You may need to logout for changes to take effect."
else
        echo "'$username' is not an admin"
        echo "Sleeping for $delay seconds staring from $(date '+%D %T')"
        sleep "$delay"
        if [[ -z "${1+x}" ]]; then
            echo "Adding '$username' to admin group"
            dscl . -append /Groups/admin GroupMembers "$uGuid"
        else
            echo "Executing command as root"
            $1
        fi
fi
